# fly.toml app configuration file generated for generate-worklog-server on 2024-01-25T15:54:26+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'generate-worklog-server'
primary_region = 'sin'

[build]
  image = 'flyio/hellofly:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
